services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./ApartmentsBackend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/apartmentdb
    volumes:
      - ./ApartmentsBackend:/app
    command: npm start

  frontend:
    build: ./apartments-app-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # volumes:
    #   - ./apartments-app-frontend:/app
    command: npm start

volumes:
  mongo-data:
